// ============================================================================
//   Ver  :| Author            :| Mod. Date :| Changes Made:
//   V1.0 :| George Totolos    :| 08/22/2016:| Initial Revision
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
	input 		          		ADC_CLK_10,
	//////////// CLOCK 1: 3.3-V LVTTL //////////
	input 		          		MAX10_CLK1_50,
	//////////// CLOCK 2: 3.3-V LVTTL //////////
	input 		          		MAX10_CLK2_50,

	//////////// LED: 3.3-V LVTTL //////////
	output		     [9:0]		LEDR,

   //////////// KEY //////////
   input            [1:0]      KEY,
	
	//////////// Arduino: 3.3-V LVTTL //////////
	inout 		    [15:0]		ARDUINO_IO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire			  	TC;
wire				reset_n;
reg	[31:0]	count;
reg				rTC;

//=======================================================
//  Structural coding
//=======================================================

assign reset_n = KEY[0];

always @(posedge MAX10_CLK2_50)
begin
	count <= count + 1;
	if(TC && ~rTC)
		rTC <= TC;
end

Counter_Top Counter_Top_0
(
	.CLK(MAX10_CLK2_50),
	.RESET(reset_n),
	.Q(ARDUINO_IO),
	.TC(TC)
);


assign LEDR = reset_n ? rTC : 10'b1010101010;

endmodule
